$ErrorActionPreference = "Stop"
py -m pip install -U yt-dlp
Write-Host ""
Write-Host "yt-dlp ist installiert oder aktualisiert."
Write-Host ""
Write-Host "Optional fuer Transkription:"
Write-Host "  py -m pip install -r requirements-transcription.txt"
Write-Host "  winget install Gyan.FFmpeg"
Write-Host ""
Write-Host "Bei TikTok-Fehlern:"
Write-Host "  In TikTok im Browser einloggen und in der App TikTok-Cookies = chrome/edge/firefox waehlen."
Write-Host "Starte die App danach mit: .\start-windows.bat"
